/**
 * SPIKE PROTOTYPE (slice 6) — scrappy, but this is the real shape.
 *
 * Serves the generated ESM shim modules that `src/pages/_document.tsx`'s import
 * map points at. Each shim re-exports the HOST's already-loaded module off
 * `window.__seerr_shared__`, so an extension panel's bare `import 'react'`
 * resolves to the SAME React instance the Seerr app tree is using.
 *
 * Why generated at runtime instead of a static file: the export list must be
 * derived from the react/react-dom that is actually installed, and Seerr ships
 * no bundler. Generation is done once at module load and cached.
 *
 * MUST be mounted ABOVE the OpenApiValidator, for the same reason
 * `/api/v1/ext` is (the validator 404s any undocumented path) — verified.
 */
import { Router } from 'express';
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import * as ReactIntl from 'react-intl';
import * as ReactJsxRuntime from 'react/jsx-runtime';
import * as Swr from 'swr';

/** Identifiers safe to re-export under their own name. */
const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

const shimSource = (specifier: string, mod: object): string => {
  const names = Object.keys(mod).filter(
    (name) => IDENTIFIER.test(name) && name !== 'default'
  );
  const key = JSON.stringify(specifier);
  return [
    `// Generated by Seerr. Re-exports the host's live '${specifier}'.`,
    `const shared = globalThis.__seerr_shared__;`,
    `if (!shared || !shared[${key}]) {`,
    `  throw new Error(`,
    `    "[seerr] '${specifier}' was imported by an extension panel before the " +`,
    `    "host published its shared modules."`,
    `  );`,
    `}`,
    `const host = shared[${key}];`,
    ...names.map((name) => `const ${name} = host.${name};`),
    `export { ${names.join(', ')} };`,
    `export default host.default !== undefined ? host.default : host;`,
    '',
  ].join('\n');
};

/**
 * `react/jsx-dev-runtime` cannot be a mechanical re-export: a panel built in dev
 * mode imports `jsxDEV`, but the host is a production React whose jsx-runtime
 * has only { Fragment, jsx, jsxs }. Adapt the signature instead of exporting
 * `undefined`, which would crash the panel on its first element.
 */
const JSX_DEV_SHIM = `// Generated by Seerr. Adapts a dev-built panel onto the host's production JSX runtime.
const shared = globalThis.__seerr_shared__;
if (!shared || !shared['react/jsx-runtime']) {
  throw new Error("[seerr] 'react/jsx-dev-runtime' imported before the host published its shared modules.");
}
const host = shared['react/jsx-runtime'];
export const Fragment = host.Fragment;
export const jsxDEV =
  host.jsxDEV ||
  function jsxDEV(type, props, key, isStaticChildren) {
    return isStaticChildren ? host.jsxs(type, props, key) : host.jsx(type, props, key);
  };
export default { Fragment, jsxDEV };
`;

const buildShims = (): Record<string, string> => ({
  'react.mjs': shimSource('react', React),
  'react-jsx-runtime.mjs': shimSource('react/jsx-runtime', ReactJsxRuntime),
  'react-jsx-dev-runtime.mjs': JSX_DEV_SHIM,
  'react-dom.mjs': shimSource('react-dom', ReactDOM),
  'react-intl.mjs': shimSource('react-intl', ReactIntl),
  'swr.mjs': shimSource('swr', Swr),
});

export const createExtensionSharedRouter = (): Router => {
  const router = Router();
  const shims = buildShims();

  router.get('/:file', (req, res) => {
    const source = shims[req.params.file];
    if (!source) {
      res.status(404).json({ status: 404, error: 'Not found' });
      return;
    }
    res.type('application/javascript; charset=utf-8');
    // Content is derived from the running build, so it is safe to cache hard
    // per-build. In real slice 6 the URL should carry the commitTag so a Seerr
    // upgrade busts it: /api/v1/ext-shared/<commitTag>/react.mjs.
    res.setHeader('Cache-Control', 'public, max-age=300');
    res.send(source);
  });

  return router;
};

export default createExtensionSharedRouter;
