/**
 * Creates this extension's one table.
 *
 * Raw SQL rather than `QueryRunner.createTable`, so that what runs is exactly
 * what is written here. Four constraints shape it:
 *
 * - **Every identifier must start with `ext_media-removal_`.** The host wraps the
 *   `QueryRunner` and inspects each statement, refusing one that touches a table
 *   outside this extension's namespace. That includes indexes, which is why the
 *   index name below is prefixed too and reads redundantly as a result.
 * - **The SQL must be valid on both sqlite and Postgres.** `integer`, `boolean`
 *   and `varchar` are spelled identically in both; the date type is not, so the
 *   two date columns are interpolated from the SDK's `resolveColumnType`. That is
 *   the same decision the entity's `DbAwareColumn` makes, which is what keeps the
 *   migrated schema and the entity metadata in agreement — and it is why the SDK
 *   exports the string form separately from the decorator, since raw SQL needs a
 *   string.
 * - **The primary key is declared rather than relying on a dialect-specific
 *   auto-increment spelling.** `GENERATED BY DEFAULT AS IDENTITY` is Postgres-only
 *   and `AUTOINCREMENT` is sqlite-only, so the column is a plain integer primary
 *   key: sqlite makes that a rowid alias, and on Postgres TypeORM's
 *   `@PrimaryGeneratedColumn` is satisfied by the sequence the *entity* metadata
 *   creates. An extension needing more than that should ship one migration per
 *   dialect and branch on `queryRunner.connection.options.type`.
 * - **The table and index names are quoted**, because the extension id contains a
 *   hyphen and an unquoted `ext_media-removal_request` parses as a subtraction.
 *
 * There is deliberately no foreign key to core's `media` or `user` tables — see
 * `../entity/RemovalRequest.ts` for why, and for what it costs.
 */
import { resolveColumnType } from '@seerr/extension-sdk';
import type { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateRemovalRequest1785600000000 implements MigrationInterface {
  name = 'CreateRemovalRequest1785600000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    const datetime = resolveColumnType('datetime');

    await queryRunner.query(
      `CREATE TABLE "ext_media-removal_request" (
        "id" integer PRIMARY KEY NOT NULL,
        "status" integer NOT NULL,
        "mediaId" integer NOT NULL,
        "is4k" boolean NOT NULL DEFAULT false,
        "mediaType" varchar NOT NULL,
        "requestedById" integer NOT NULL,
        "modifiedById" integer,
        "createdAt" ${datetime} NOT NULL,
        "updatedAt" ${datetime} NOT NULL
      )`
    );
    await queryRunner.query(
      `CREATE INDEX "ext_media-removal_request_status" ON "ext_media-removal_request" ("status")`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX "ext_media-removal_request_status"`);
    await queryRunner.query(`DROP TABLE "ext_media-removal_request"`);
  }
}
