/**
 * Serves the ESM shim modules that an extension panel's bare imports resolve to.
 *
 * A panel is a pre-built ESM bundle loaded at runtime by `import()`, so it
 * cannot be bundled together with the host — but it must nevertheless use the
 * host's *same* React instance, or its first hook throws the null-dispatcher
 * error. Two halves make that work, and both are required:
 *
 * 1. `src/pages/_app.tsx` publishes the host's live modules on
 *    `window.__seerr_shared__` at module scope.
 * 2. The import map in `src/pages/_document.tsx` redirects each bare specifier
 *    to a URL served here, and the shim re-exports off that global.
 *
 * The map alone has nothing to point at; the global alone does not intercept
 * bare specifiers. Neither can be replaced by importing React directly: React
 * 19 ships no ESM build at all, and Next never emits `<script type="module">`,
 * so its own chunks are unaffected by the map.
 *
 * The trap this avoids is quiet: `react.production.js` has zero `require()`
 * calls, so it wraps into a loadable ESM module trivially and renders fine as a
 * *second* React instance, failing only later on a hook. Nothing here may
 * construct a module; every binding is read off the host global.
 *
 * MUST be mounted **above** the OpenAPI validator, for the same reason
 * `/api/v1/ext` is — see Constraint 3 in docs/specs/extension-system.md and the
 * comment at the mount site in `server/index.ts`. Unlike extension routes these
 * are not behind `checkUser`: they are static, non-secret re-export stubs, and
 * the browser resolves an import map with no credentials guarantee.
 */
import { getCommitTag } from '@server/utils/appVersion';
import { Router } from 'express';
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import * as ReactDOMClient from 'react-dom/client';
import * as ReactIntl from 'react-intl';
import * as ReactJsxRuntime from 'react/jsx-runtime';
import * as Swr from 'swr';

/**
 * Every bare specifier a panel may import and get the host's copy of.
 *
 * This list must be **exhaustive** with respect to what panels import: an
 * unmapped specifier does not error at build time, it resolves to a second copy
 * of the package at runtime. Note that `react-dom` does not cover
 * `react-dom/client` — subpaths are separate map entries.
 */
export const SHARED_MODULE_SPECIFIERS = [
  'react',
  'react/jsx-runtime',
  'react/jsx-dev-runtime',
  'react-dom',
  'react-dom/client',
  'react-intl',
  'swr',
] as const;

export type SharedModuleSpecifier = (typeof SHARED_MODULE_SPECIFIERS)[number];

/** The filename a specifier is served as, e.g. `react/jsx-runtime` → `react-jsx-runtime.mjs`. */
export function sharedModuleFilename(specifier: SharedModuleSpecifier): string {
  return `${specifier.replace(/\//g, '-')}.mjs`;
}

/**
 * The mount path, carrying the build tag so a Seerr upgrade busts any cached
 * shim. The tag is not a lookup key — a running process has exactly one build —
 * it only has to change when the host's module surface might have.
 */
export const SHARED_MODULE_BASE_PATH = '/api/v1/ext-shared';

/** The URL `_document.tsx`'s import map should point a specifier at. */
export function sharedModuleUrl(
  specifier: SharedModuleSpecifier,
  buildTag: string
): string {
  return `${SHARED_MODULE_BASE_PATH}/${buildTag}/${sharedModuleFilename(specifier)}`;
}

/** Identifiers safe to re-export under their own name. */
const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * A shim re-exporting the host's live module.
 *
 * The export list is derived from the *installed* package rather than
 * hand-written, so a panel using something the host has cannot get `undefined`
 * for it, and a dependency upgrade needs no edit here.
 */
function shimSource(specifier: string, mod: object): string {
  const names = Object.keys(mod).filter(
    (name) => IDENTIFIER.test(name) && name !== 'default'
  );
  const key = JSON.stringify(specifier);

  return [
    `// Generated by Seerr. Re-exports the host's live '${specifier}'.`,
    `const shared = globalThis.__seerr_shared__;`,
    `if (!shared || !shared[${key}]) {`,
    `  throw new Error(`,
    `    "[seerr] '${specifier}' was imported by an extension panel before the " +`,
    `    "host published its shared modules."`,
    `  );`,
    `}`,
    `const host = shared[${key}];`,
    ...names.map((name) => `const ${name} = host.${name};`),
    `export { ${names.join(', ')} };`,
    `export default host.default !== undefined ? host.default : host;`,
    '',
  ].join('\n');
}

/**
 * `react/jsx-dev-runtime` cannot be a mechanical re-export: a panel built in dev
 * mode imports `jsxDEV`, but a production host's jsx-runtime has only
 * `{ Fragment, jsx, jsxs }`. Adapting the signature keeps such a panel working;
 * re-exporting `undefined` would crash it on its first element.
 */
const JSX_DEV_SHIM = `// Generated by Seerr. Adapts a dev-built panel onto the host's JSX runtime.
const shared = globalThis.__seerr_shared__;
if (!shared || !shared['react/jsx-runtime']) {
  throw new Error(
    "[seerr] 'react/jsx-dev-runtime' was imported by an extension panel before " +
    "the host published its shared modules."
  );
}
const host = shared['react/jsx-runtime'];
export const Fragment = host.Fragment;
export const jsxDEV =
  host.jsxDEV ||
  function jsxDEV(type, props, key, isStaticChildren) {
    return isStaticChildren ? host.jsxs(type, props, key) : host.jsx(type, props, key);
  };
export default { Fragment, jsxDEV };
`;

/**
 * Built once at module load: the source depends only on what is installed, and
 * generating per request would re-walk every module's key list.
 */
function buildShims(): Map<string, string> {
  const hostModules: Record<string, object> = {
    react: React,
    'react/jsx-runtime': ReactJsxRuntime,
    'react-dom': ReactDOM,
    'react-dom/client': ReactDOMClient,
    'react-intl': ReactIntl,
    swr: Swr,
  };

  const shims = new Map<string, string>();

  for (const specifier of SHARED_MODULE_SPECIFIERS) {
    const filename = sharedModuleFilename(specifier);

    shims.set(
      filename,
      specifier === 'react/jsx-dev-runtime'
        ? JSX_DEV_SHIM
        : shimSource(specifier, hostModules[specifier])
    );
  }

  return shims;
}

export function createExtensionSharedRouter(): Router {
  const router = Router();
  const shims = buildShims();

  // `:buildTag` is accepted and ignored: it exists to make the URL change across
  // upgrades, not to select anything. Serving every tag from this build's shims
  // is correct, since this build is the only one this process can share.
  router.get('/:buildTag/:file', (req, res) => {
    const source = shims.get(req.params.file);

    if (!source) {
      res.status(404).json({ status: 404, error: 'Not found' });
      return;
    }

    res.type('application/javascript; charset=utf-8');
    // Safe to cache hard: the content is fixed by the build, and the build tag
    // in the path changes when the build does.
    res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
    res.send(source);
  });

  router.use((_req, res) => {
    res.status(404).json({ status: 404, error: 'Not found' });
  });

  return router;
}

/** The import map body for `_document.tsx`, as a JSON string. */
export function sharedModuleImportMap(buildTag = getCommitTag()): string {
  return JSON.stringify({
    imports: Object.fromEntries(
      SHARED_MODULE_SPECIFIERS.map((specifier) => [
        specifier,
        sharedModuleUrl(specifier, buildTag),
      ])
    ),
  });
}

export default createExtensionSharedRouter;
