/**
 * Creates this extension's one table.
 *
 * Written as raw SQL rather than with `QueryRunner.createTable`, so that what
 * runs is exactly what is written here. Two constraints shape it:
 *
 * - **Every identifier must start with `ext_watch-history_`.** The host wraps the
 *   `QueryRunner` and inspects each statement, refusing one that touches a table
 *   outside this extension's namespace. That includes indexes.
 * - **The SQL must be valid on both sqlite and Postgres**, which is why the
 *   columns are `integer`/`varchar`/`bigint` — spelled identically in both — and
 *   why the primary key is declared rather than relying on a dialect-specific
 *   auto-increment spelling. `GENERATED BY DEFAULT AS IDENTITY` is Postgres-only
 *   and `AUTOINCREMENT` is sqlite-only, so the column is a plain integer primary
 *   key: sqlite makes that a rowid alias, and on Postgres TypeORM's
 *   `@PrimaryGeneratedColumn` is satisfied by the sequence the *entity* metadata
 *   creates. An extension needing more than that should ship one migration per
 *   dialect and branch on `queryRunner.connection.options.type`.
 *
 * The table name is quoted because the id contains a hyphen.
 */
import type { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateWatchEvent1754280000000 implements MigrationInterface {
  name = 'CreateWatchEvent1754280000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "ext_watch-history_event" (
        "id" integer PRIMARY KEY NOT NULL,
        "userId" integer NOT NULL,
        "mediaId" integer NOT NULL,
        "mediaType" varchar NOT NULL,
        "tmdbId" integer,
        "source" varchar NOT NULL DEFAULT 'event',
        "watchedAt" bigint NOT NULL
      )`
    );
    await queryRunner.query(
      `CREATE INDEX "ext_watch-history_event_user_watched" ON "ext_watch-history_event" ("userId", "watchedAt")`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX "ext_watch-history_event_user_watched"`
    );
    await queryRunner.query(`DROP TABLE "ext_watch-history_event"`);
  }
}
