/**
 * Creates this extension's one table.
 *
 * Raw SQL rather than `QueryRunner.createTable`, so what runs is exactly what is
 * written here. The constraints, all of them the same ones
 * `watch-history`'s migration documents:
 *
 * - **Every identifier must start with `ext_watch-stats_`**, indexes included:
 *   the host wraps the `QueryRunner` and refuses a statement touching a table
 *   outside this extension's namespace.
 * - **The SQL must be valid on both sqlite and Postgres.** `integer`, `varchar`
 *   and `bigint` are spelled identically; the date type is not, so it is
 *   interpolated from the SDK's `resolveColumnType` — the same decision the
 *   entity's `DbAwareColumn` makes, which is what keeps the migrated schema and
 *   the entity metadata in agreement.
 * - **The primary key is a plain integer**, because `AUTOINCREMENT` is
 *   sqlite-only and `GENERATED BY DEFAULT AS IDENTITY` is Postgres-only. sqlite
 *   makes it a rowid alias; on Postgres the sequence comes from the entity
 *   metadata's `@PrimaryGeneratedColumn`.
 *
 * The table name is quoted because the id contains a hyphen.
 */
import { resolveColumnType } from '@constructorfleet/extension-sdk';
import type { MigrationInterface, QueryRunner } from 'typeorm';

export class CreatePlayStat1786000000000 implements MigrationInterface {
  name = 'CreatePlayStat1786000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    const date = resolveColumnType('datetime');

    await queryRunner.query(
      `CREATE TABLE "ext_watch-stats_play" (
        "id" integer PRIMARY KEY NOT NULL,
        "userId" integer NOT NULL,
        "mediaId" integer NOT NULL,
        "mediaType" varchar NOT NULL,
        "plays" integer NOT NULL DEFAULT 0,
        "watchTimeMs" bigint NOT NULL DEFAULT 0,
        "lastPlayedAt" ${date},
        "source" varchar NOT NULL DEFAULT 'tautulli',
        "syncedAt" ${date} NOT NULL
      )`
    );
    // The unique constraint is what makes the sync's "recompute and replace"
    // safe, so it is created with the table rather than left to the entity
    // metadata — a schema built by migration must match one built by synchronize.
    await queryRunner.query(
      `CREATE UNIQUE INDEX "ext_watch-stats_play_user_media" ON "ext_watch-stats_play" ("userId", "mediaId")`
    );
    await queryRunner.query(
      `CREATE INDEX "ext_watch-stats_play_user_plays" ON "ext_watch-stats_play" ("userId", "plays")`
    );
    await queryRunner.query(
      `CREATE INDEX "ext_watch-stats_play_media" ON "ext_watch-stats_play" ("mediaId")`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX "ext_watch-stats_play_media"`);
    await queryRunner.query(`DROP INDEX "ext_watch-stats_play_user_plays"`);
    await queryRunner.query(`DROP INDEX "ext_watch-stats_play_user_media"`);
    await queryRunner.query(`DROP TABLE "ext_watch-stats_play"`);
  }
}
